spring:
#저장파일 최대 용량 조절
 servlet:
    multipart:
      maxFileSize: 200MB
      maxRequestSize: 215MB
       
#db-mysql
 datasource:
      url: jdbc:mysql://localhost:3306/jsptest
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: jspid
      password: jsppass

mybatis:
#  dto alias를 설정
   type-aliases-package: jjon.bamyanggang.*
   mapper-locations: classpath:/mapper/*.xml
   config-location: classpath:Mybatis-Config.xml

#port
server:
  port: 80

